AlzaBox.API.WebExample/Pages/Box.cshtml.cs
using AlzaBox.API.Clients;
using AlzaBox.API.WebExample.Models;
using Microsoft.AspNetCore.Mvc;


namespace AlzaBox.API.WebExample.Pages;
public class Box : BasePageModel
{
    public AlzaBox.API.Models.Box? BoxData { get; set; }
    
    [BindProperty]
    public PackageSizeModel PackageSize { get; set; }
    public float? Occupancy { get; set; }
    
    private readonly ABAPIService _abapi;

    [BindProperty]
    public int BoxId { get; set; }

    public Box(ABAPIService abapiService)
    {
        _abapi = abapiService;
        _abapi.IsSignedIn(true);
    }
    
    public async Task<IActionResult> OnGet(int id)
    {
        var boxes = await _abapi.client.Boxes.Get(id);
        BoxData = boxes.Data[0];
        BoxId = id;
        
        return Page();        
    }
    public async Task<IActionResult> OnGetWithOccupancy(int id)
    {
        var boxes = await _abapi.client.Boxes.Get(id);
        BoxData = boxes.Data[0];
        BoxId = id;
        Occupancy = await _abapi.client.Boxes.GetBoxOccupancy(id);
        
        return Page();
    }

    public async Task<IActionResult> OnPostPackage()
    {
        if (PackageSize.Width.HasValue && PackageSize.Height.HasValue && PackageSize.Depth.HasValue)
        {
            var boxResponse = await _abapi.client.Boxes.GetBoxFitting(PackageSize.Width.Value, PackageSize.Height.Value,
                PackageSize.Depth.Value, BoxId);
            BoxData = boxResponse.Data[0];
        }
        else
        {
            var boxes = await _abapi.client.Boxes.Get(BoxId);
            BoxData = boxes.Data[0];
        }
        
        return Page();
    }
}

AlzaBox.API.WebExample/Pages/Boxes.cshtml.cs
using System.Data;
using AlzaBox.API.WebExample.Models;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;


namespace AlzaBox.API.WebExample.Pages;

public class Boxes : BasePageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly ABAPIService _abapi;

    [BindProperty]
    public BoxSearchModel? BoxSearch { get; set; }
    public List<AlzaBox.API.Models.Box>? BoxesData { get; set; }
    
    public Boxes(ILogger<IndexModel> logger, ABAPIService abapiService)
    {
        _abapi = abapiService; 
        _abapi.IsSignedIn(true);
    }

    public async Task<IActionResult> OnGet()
    {
        BoxesData = new List<AlzaBox.API.Models.Box>();
        try
        {
            var boxes = await _abapi.client.Boxes.GetAll();
            BoxesData = boxes.Data;
        }
        catch (HttpRequestException ex)
        {
            SetFlash(FlashMessageType.Danger, ex.Source + ex.Message);
        }

        return Page();
    }

    public async Task<IActionResult> OnPostSearch()
    {
        BoxesData = new List<AlzaBox.API.Models.Box>();
        
        if (!string.IsNullOrWhiteSpace(BoxSearch.Id))
        {
            var boxId = int.Parse(BoxSearch.Id);
            var boxes = await _abapi.client.Boxes.Get(boxId);
            BoxesData.AddRange(boxes.Data);
            return Page();
        }
        
        if (!string.IsNullOrWhiteSpace(BoxSearch.Name))
        {
            var boxes = await _abapi.client.Boxes.GetByName(BoxSearch.Name);
            BoxesData.AddRange(boxes.Data);
            return Page();
        }

        var allboxes = await _abapi.client.Boxes.GetAll();
        BoxesData.AddRange(allboxes.Data);
        
        return Page();
    }
    
    public async Task<FileResult> OnPostExport()
    {
        var allboxes = await _abapi.client.Boxes.GetAll();
        var boxesflat = new List<BoxFlatModel>();

        foreach (var box in allboxes.Data)
        {
             boxesflat.Add(new BoxFlatModel()
             {
                 Id = box.Id,
                 Name = box.Attributes.Name,
                 Lat = box.Attributes.Gps.Lat,
                 Lng = box.Attributes.Gps.Lng,
                 City = box.Attributes.Adress.City,
                 StreetWithNumber = box.Attributes.Adress.StreetWithNumber,
                 ZIP = box.Attributes.Adress.Zip,
                 Description = box.Attributes.Description,
                 CountryShortCode = box.Attributes.CountryShortCode
             });
        }
        
        DataTable dt = new DataTable("Grid");
        dt.Columns.AddRange(new DataColumn[9] 
        { new DataColumn("Id"),
            new DataColumn("Name"),
            new DataColumn("Description"),
            new DataColumn("StreetWithNumber"), 
            new DataColumn("City"),
            new DataColumn("ZIP"),
            new DataColumn("CountryShortCode"),
            new DataColumn("Lat"),            
            new DataColumn("Lng")
        });
        
        foreach (var box in boxesflat)
        {
            dt.Rows.Add(box.Id, box.Name, box.Description, box.StreetWithNumber, box.City, box.ZIP, box.CountryShortCode, box.Lat, box.Lng);
        }
 
        using (XLWorkbook wb = new XLWorkbook())
        {
            wb.Worksheets.Add(dt);
            using (MemoryStream stream = new MemoryStream())
            {
                wb.SaveAs(stream);
                return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "AlzaBoxes.xlsx");
            }
        }
    }
}

AlzaBox.API.WebExample/Pages/Courier.cshtml.cs
using AlzaBox.API.Models;
using AlzaBox.API.WebExample.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlzaBox.API.WebExample.Pages;

public class Courier : BasePageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly ABAPIService _abapi;

    [BindProperty] public API.Models.CourierWithAttributes Entity { get; set; }
    
    [BindProperty] public AddBoxModel AddBoxEntity { get; set; }

    public string? Action;

    public Courier(ILogger<IndexModel> logger, ABAPIService abapiService)
    {
        _logger = logger;
        _abapi = abapiService;
        _abapi.IsSignedIn(true);
    }

    public async Task<IActionResult> OnGetCreateCourier()
    {

        Entity = new API.Models.CourierWithAttributes()
        {
        };

        SetFlash(FlashMessageType.Info, "Creating courier");
        Action = "Create";
        return Page();
    }
    
    public async Task<IActionResult> OnGetUpdateCourier(string login)
    {
        var couriersResponse = await _abapi.client.Couriers.Get(login);
        Entity = couriersResponse.Data.Couriers.FirstOrDefault();

        SetFlash(FlashMessageType.Info, "Updating courier");
        Action = "Update";
        return Page();
    }
    
    public async Task<IActionResult> OnGetAddBox(string login)
    {
        var couriersResponse = await _abapi.client.Couriers.Get(login);
        Entity = couriersResponse.Data.Couriers.FirstOrDefault();

        SetFlash(FlashMessageType.Info, "Updating courier");
        Action = "AddBox";
        return Page();
    }
    
    public async Task<IActionResult> OnGetRemoveBox(string login, int boxId)
    {
        var couriersResponse = await _abapi.client.Couriers.Get(login);
        var courier = couriersResponse.Data.Couriers.FirstOrDefault();
        var boxes = courier.Attributes.Boxes;
        var boxToRemove = boxes.FirstOrDefault(x => x.Id == boxId);
        boxes.Remove(boxToRemove);
        var updateResponse = await _abapi.client.Couriers.Update(courier.Login, courier.Pin, boxes);

        SetFlash(FlashMessageType.Info, "Removing box");
        
        return RedirectToPage("/courier", new { login = login });
    }
    
    public async Task<IActionResult> OnGet(string login)
    {
        try
        {
            var courierResponse = await _abapi.client.Couriers.Get(login);
            Entity = courierResponse.Data.Couriers.FirstOrDefault();
        }
        catch (Exception ex)
        {
            SetFlash(FlashMessageType.Danger, ex.Source + ex.Message);
        }

        return Page();
    }
    
    public async Task<IActionResult> OnPost()
    {
        var response = await _abapi.client.Couriers.Create(Entity.Login, Entity.Pin, null);

        if (response.Data != null)
        {
            Entity = response.Data;
            SetFlash(FlashMessageType.Info, "Courier created");
        }
        else
        {
            //Entity = new API.Models.Courier()
            SetFlash(FlashMessageType.Danger, response.Metadata);
        }

        return Page();
    }    
    
    public async Task<IActionResult> OnPostUpdate()
    {
        var response = await _abapi.client.Couriers.Update(Entity.Login, Entity.Pin, null);

        if (response.Data != null)
        {
            Entity = response.Data;
            SetFlash(FlashMessageType.Info, "Courier updated");
        }
        else
        {
            //Entity = new API.Models.Courier()
            SetFlash(FlashMessageType.Danger, response.Metadata);
        }
        
        Action = "Update";
        return Page();
    }
    
    public async Task<IActionResult> OnPostAddBox()
    {
        var couriersResponse = await _abapi.client.Couriers.Get(AddBoxEntity.Login);
        var boxes = couriersResponse.Data.Couriers.FirstOrDefault().Attributes.Boxes;
        if (boxes == null)
        {
            boxes = new List<CourierBox>();
        }
        
        boxes.Add(new CourierBox()
        {
            Id = AddBoxEntity.BoxId
        });
        
        var response = await _abapi.client.Couriers.Update(Entity.Login, Entity.Pin, boxes);

        if (response.Data != null)
        {
            Entity = response.Data;
            SetFlash(FlashMessageType.Info, "Box added");
        }
        else
        {
            //Entity = new API.Models.Courier()
            SetFlash(FlashMessageType.Danger, response.Metadata);
        }
        
        Action = "Update";
        return Page();
    }    
}

AlzaBox.API.WebExample/Pages/CourierAddBox.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlzaBox.API.WebExample.Pages;

public class CourierAddBox : PageModel
{
    public void OnGet()
    {
        
    }
}

AlzaBox.API.WebExample/Pages/Couriers.cshtml.cs
using AlzaBox.API.WebExample.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AlzaBox.API.WebExample.Pages;

public class Couriers : BasePageModel
{

    private readonly ILogger<IndexModel> _logger;
    private readonly ABAPIService _abapi;

    public List<AlzaBox.API.Models.CourierWithAttributes>? CouriersData { get; set; }
    
    public Couriers(ILogger<IndexModel> logger, ABAPIService abapiService)
    {
        _abapi = abapiService; 
        _abapi.IsSignedIn(true);
    }
    
    public async Task<IActionResult> OnGet()
    {
        CouriersData = new List<AlzaBox.API.Models.CourierWithAttributes>();
        try
        {
            var boxes = await _abapi.client.Couriers.Get();
            CouriersData = boxes.Data.Couriers;
        }
        catch (HttpRequestException ex)
        {
            SetFlash(FlashMessageType.Danger, ex.Source + ex.Message);
        }

        return Page();
    }    

    
}

AlzaBox.API.WebExample/Pages/Reservation.cshtml.cs
using AlzaBox.API.WebExample.Core.Extensions;
using AlzaBox.API.WebExample.Models;
using Microsoft.AspNetCore.Mvc;

namespace AlzaBox.API.WebExample.Pages;

public class Reservation : BasePageModel
{
    private readonly ILogger<IndexModel> _logger;

    [BindProperty] public Models.ReservationModel Entity { get; set; }

    public string? Action;

    public AlzaBox.API.Models.Box? BoxData { get; set; }
    private readonly ABAPIService _abapi;

    public Reservation(ILogger<IndexModel> logger, ABAPIService abapiService)
    {
        _logger = logger;
        _abapi = abapiService;
        _abapi.IsSignedIn(true);
    }
    
    public async Task<IActionResult> OnGet(string id)
    {
        try
        {
            var reservationsResponse = await _abapi.client.Reservations.Get(id);
            var reservation = reservationsResponse.Data.FirstOrDefault();
            Entity = Entity.Map(reservation);
            var boxes = await _abapi.client.Boxes.Get(Entity.BoxId);
            BoxData = boxes.Data[0];
        }
        catch (Exception ex)
        {
            SetFlash(FlashMessageType.Danger, ex.Source + ex.Message);
        }
        
        return Page();
    }

    public async Task<IActionResult> OnGetCancel(string id)
    {
        var reservationResponse = await _abapi.client.Reservations.Cancel(id);
        if (reservationResponse.Data != null)
        {
            Entity = Entity.Map(reservationResponse.Data);
            var boxes = await _abapi.client.Boxes.Get(Entity.BoxId);
            BoxData = boxes.Data[0];
            SetFlash(FlashMessageType.Info, "Reservation was cancelled");
        }
        else
        {
            var reservationsResponse = await _abapi.client.Reservations.Get(id);
            var reservation = reservationsResponse.Data.FirstOrDefault();
            Entity = Entity.Map(reservation);
            var boxes = await _abapi.client.Boxes.Get(Entity.BoxId);
            BoxData = boxes.Data[0];
            SetFlash(FlashMessageType.Danger, reservationResponse.Metadata);
        }

        return Page();
    }

    public async Task<IActionResult> OnGetExtend(string id)
    {
        try
        {
            var reservationsResponse = await _abapi.client.Reservations.Get(id);
            var reservation = reservationsResponse.Data.FirstOrDefault();
            Entity = Entity.Map(reservation);
            var boxes = await _abapi.client.Boxes.Get(Entity.BoxId);
            BoxData = boxes.Data[0];
            Action = "Extend";
            SetFlash(FlashMessageType.Info, "Extending reservation");
        }
        catch (Exception ex)
        {
            SetFlash(FlashMessageType.Danger, ex.Message);
        }

        return Page();
    }

    public async Task<IActionResult> OnPostExtend()
    {
        var reservationResponse = await _abapi.client.Reservations.Extend(Entity.Id, Entity.ExpirationDate);
        if (reservationResponse.Data != null)
        {
            Entity = Entity.Map(reservationResponse.Data);
            var boxes = await _abapi.client.Boxes.Get(Entity.BoxId);
            BoxData = boxes.Data[0];

            SetFlash(FlashMessageType.Info, "Reservation extended");
        }
        else
        {
            var reservationsResponse = await _abapi.client.Reservations.Get(Entity.Id);
            var reservation = reservationsResponse.Data.FirstOrDefault();
            Entity = Entity.Map(reservation);
            var boxes = await _abapi.client.Boxes.Get(Entity.BoxId);
            BoxData = boxes.Data[0];

            SetFlash(FlashMessageType.Danger, reservationResponse.Metadata);
        }

        Action = "Extend";
        return Page();
    }

    public async Task<IActionResult> OnGetCreateReservation(int boxId)
    {
        var boxes = await _abapi.client.Boxes.Get(boxId);
        BoxData = boxes.Data[0];

        Entity = new ReservationModel()
        {
            Id = Guid.NewGuid().ToString(),
            BoxId = BoxData.Id,
            ExpirationDate = DateTime.Now.AddHours(1)
        };

        SetFlash(FlashMessageType.Info, "Creating reservation");
        Action = "Create";
        return Page();
    }

    public async Task<IActionResult> OnPost()
    {
        var boxes = await _abapi.client.Boxes.Get(Entity.BoxId);
        BoxData = boxes.Data[0];
        
        var response = await _abapi.client.Reservations.Reserve(Entity.Id.ToString(), Entity.BoxId, Entity.PackageNumber,
            Entity.ExpirationDate,
            Entity.Depth, Entity.Height, Entity.Width);

        if (response.Data != null)
        {
            Entity = Entity.Map(response.Data);
            SetFlash(FlashMessageType.Info, "Reservation created");
        }
        else
        {
            Entity = new ReservationModel();
            SetFlash(FlashMessageType.Danger, response.Metadata);
        }

        return Page();
    }
}

AlzaBox.API.WebExample/Pages/VirtualBox.cshtml.cs
using AlzaBox.API.WebExample.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using AlzaBox.API.V2.Clients;
using AlzaBox.API.V2.Models;

namespace AlzaBox.API.WebExample.Pages;

public class VirtualBox : BasePageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly ABAPIService _abapi;
    public string? Action;
    
    [BindProperty] 
    public Models.VirtualBoxModel Entity { get; set; }

    public VirtualBox(ILogger<IndexModel> logger, ABAPIService abapiService)
    {
        _logger = logger;
        _abapi = abapiService;
        _abapi.IsSignedIn(true);
    }
    
    public void OnGet()
    {
        Entity = new VirtualBoxModel();
    }

    public async Task<IActionResult> OnPostStock()
    {
        try
        {
            _abapi.clientV2.VirtualBox.Stocked(Entity.Id);
            SetFlash(FlashMessageType.Info, "Reservation was stocked");
        }
        catch (Exception ex)
        {
            SetFlash(FlashMessageType.Warning, $"VirtualBox error: {ex.Message}");
            _logger.LogError($"VirtualBox error: {ex.Message}", ex);
        }
        
        return Page();
    }
    
    public async Task<IActionResult> OnPostCustomerPickup()
    {
        try
        {
            _abapi.clientV2.VirtualBox.PickedUp(Entity.Id);
            SetFlash(FlashMessageType.Info, "Reservation PickedUp");
        }
        catch (Exception ex)
        {
            SetFlash(FlashMessageType.Warning, $"VirtualBox error: {ex.Message}");
            _logger.LogError($"VirtualBox error: {ex.Message}", ex);
        }

        return Page();
    }
}

AlzaBox.API.WebExample/Pages/Box.cshtml
@page "{id}"
@model AlzaBox.API.WebExample.Pages.Box

@{
    ViewData["Title"] = $"AlzaBox {Model.BoxData.Id} {Model.BoxData.Attributes.Name}";
}

<div class="pricing-header p-3 pb-md-4 mx-auto text-center">

    <p>@Model.BoxData.Attributes.Adress.StreetWithNumber @Model.BoxData.Attributes.Adress.Zip @Model.BoxData.Attributes.Adress.City</p>
    <p>@Model.BoxData.Attributes.Description</p>


    <div class="form-group">
        <a asp-page="box" asp-route-boxid="@Model.BoxData.Id" asp-page-handler="WithOccupancy" class="btn btn-primary">Get occupancy</a>
        <a asp-page="reservation" asp-route-boxid="@Model.BoxData.Id" asp-page-handler="CreateReservation" class="btn btn-primary">Create reservation</a>
        <a asp-page="boxes" class="btn btn-secondary">Back</a>
    </div>

</div>

<div class="row row-cols-1 row-cols-md-3 mb-3">
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Openning hours</h4>
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>
                            Day
                        </th>
                        <th>
                            Open
                        </th>
                        <th>
                            Close
                        </th>
                    </tr>
                    </thead>
                    @foreach (var boxOpeningHour in @Model.BoxData.Attributes.OpeningHours)
                    {
                        <tr>
                            <td>@boxOpeningHour.Day</td>
                            <td>@boxOpeningHour.Open</td>
                            <td>@boxOpeningHour.Close</td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Attributes</h4>
            </div>
            <div class="card-body">
                <table class="table table-striped table-responsive">
                    <tr>
                        <td>Delivery Pin</td>
                        <td>@Model.BoxData.Attributes.DeliveryPin</td>
                    </tr>
                    <tr>
                        <td>Gps Lat</td>
                        <td id="lat">@Model.BoxData.Attributes.Gps.Lat</td>
                    </tr>
                    <tr>
                        <td>Gps Lng</td>
                        <td id="lng">@Model.BoxData.Attributes.Gps.Lng</td>
                    </tr>
                    <tr>
                        <td>Occupancy</td>
                        <td>@Model.Occupancy</td>
                    </tr>
                    <tr>
                        <td>Unavaiable Reason</td>
                        <td></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Packages</h4>
            </div>
            <div class="card-body">
                <form method="post" class="row g-3">
                    <input asp-for="BoxId" hidden="hidden"/>

                    <div class="form-group">
                        <label asp-for="PackageSize.Width" class="form-label"></label>
                        <input asp-for="PackageSize.Width" class="form-control"/>
                        <span asp-validation-for="PackageSize.Width" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PackageSize.Height" class="form-label"></label>
                        <input asp-for="PackageSize.Height" class="form-control"/>
                        <span asp-validation-for="PackageSize.Height" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PackageSize.Depth" class="form-label"></label>
                        <input asp-for="PackageSize.Depth" class="form-control"/>
                        <span asp-validation-for="PackageSize.Depth" class="text-danger"></span>
                    </div>

                    <button type="submit" asp-page="Box" asp-page-handler="Package" class="btn btn-primary">Is package fit?</button>
                </form>

                <h5 visible="(@Model.BoxData.Attributes.FittingPackages != null)" style="padding-top: 15px">Fitting packages</h5>
                <table visible="(@Model.BoxData.Attributes.FittingPackages != null)" class="table table-striped table-responsive">
                    @foreach (var item in @Model.BoxData.Attributes.FittingPackages)
                    {
                        <tr>
                            <td>@item.Width</td>
                            <td>@item.Height</td>
                            <td>@item.Depth</td>
                        </tr>
                    }
                </table>
                <h5 visible="(@Model.BoxData.Attributes.TooLargePackages?.Count > 0)">Too large packages</h5>
                <table visible="(@Model.BoxData.Attributes.TooLargePackages != null)" class="table table-striped table-responsive">
                    @foreach (var item in @Model.BoxData.Attributes.TooLargePackages)
                    {
                        <tr>
                            <td>@item.Width</td>
                            <td>@item.Height</td>
                            <td>@item.Depth</td>
                        </tr>
                    }
                </table>
                @if (@Model.BoxData.Attributes.RequiredSlots != null)
                {
                    <h5>Required slots</h5>
                    <ol>
                        @foreach (var item in @Model.BoxData.Attributes.RequiredSlots)
                        {
                            <li>
                                Count: @item.Count, &nbsp;
                                Type: @item.Type, &nbsp;
                                AvaiableCount: @item.AvailableCount, &nbsp;
                                MaxCount: @item.MaxCount, &nbsp;
                                TotalCount: @item.TotalCount, &nbsp;
                            </li>
                        }
                    </ol>
                }
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3 text-bg-primary">
                <h4 class="my-0 fw-normal">Slots</h4>
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>
                            Count
                        </th>
                        <th>
                            Depth
                        </th>
                        <th>
                            Height
                        </th>
                        <th>
                            Width
                        </th>
                        <th>
                            Type
                        </th>
                        <th>
                            Id
                        </th>
                    </tr>
                    </thead>
                    @foreach (var boxSlot in @Model.BoxData.Attributes.Slots)
                    {
                        <tr>
                            <td>@boxSlot.Count</td>
                            <td>@boxSlot.Depth</td>
                            <td>@boxSlot.Height</td>
                            <td>@boxSlot.Width</td>
                            <td>@boxSlot.Type</td>
                            <td>@boxSlot.SlotId</td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card rounded-3 shadow-sm">
            <div class="card-header py-3 text-bg-primary">
                <h4 class="my-0 fw-normal">Map</h4>
            </div>
            <div class="card-body">
                <div id="map">Map</div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"/>
    <style>
          html, body {
            height: 100%;
            padding: 0;
            margin: 0;
          }
          #map {
            /* configure the size of the map */
            width: 100%;
            height: 500px;
          }
    </style>
}

@section Scripts {
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <script>
      let lng = $('#lng').html();
      let lat = $('#lat').html();
                                   
      var map = L.map('map').setView({lon: lng, lat: lat}, 12);
      
      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
      }).addTo(map);

      L.control.scale({imperial: true, metric: true}).addTo(map);
      L.marker({lon: lng, lat: lat}).addTo(map);
    </script>
}

AlzaBox.API.WebExample/Pages/Courier.cshtml
@page
@model AlzaBox.API.WebExample.Pages.Courier

@{
}

<form method="post" class="row g-3">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Entity.Login" class="form-label"></label>
        <input asp-for="Entity.Login" class="form-control"/>
        <span asp-validation-for="Entity.Login" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Entity.Pin" class="form-label"></label>
        <input asp-for="Entity.Pin" class="form-control"/>
        <span asp-validation-for="Entity.Pin" class="text-danger"></span>
    </div>

    <div class="form-group">
        @if (Model.Action == "Create")
        {
            <input type="submit" value="Create" class="btn btn-primary"/>
        }
        else
        {
            @if (Model.Action == "Update")
            {
                <input type="submit" asp-page-handler="Update" value="Update courier" class="btn btn-primary"/>
            }
        }

        <a asp-page="/Couriers" class="btn btn-link">Couriers</a>
        <a asp-page="/Index" class="btn btn-link">Home</a>
    </div>

    @if (Model.Action == "Update")
    {
        <div class="form-group">
            <a asp-page="/Courier" asp-page-handler="AddBox" class="btn btn-primary">Add box</a>
        </div>

        <ul>
            @if ((@Model.Entity.Attributes != null) && (@Model.Entity.Attributes.Boxes != null))
            {
                @foreach (var courierBox in @Model.Entity.Attributes.Boxes)
                {
                    <li>ID: @courierBox.Id PID: @courierBox.Pid <a asp-page="/Courier" asp-page-handler="RemoveBox" asp-route-boxId="@courierBox.Id" asp-route-login="@Model.Entity.Login" class="btn btn-link">Remove box</a></li>
                }
            }
        </ul>
    }

    @if (Model.Action == "AddBox")
    {
        <form method="post" class="row g-3">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label class="form-label">Box Id</label>
                <input Id="BoxId" name="BoxId" class="form-control"/>
            </div>
            <div class="form-group">
                <input type="submit" asp-page-handler="AddBox" value="Add box access" class="btn btn-primary"/>
            </div>
        </form>
    }
</form>